name: Release new version

on:
  milestone:
    types: [closed]

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Prune and get tags
        run: git fetch --prune --unshallow --tags

      - name: Create changelog file
        run: git log $(git describe --tags --abbrev=0)..HEAD --oneline --no-merges | sed -e 's/^/\* /' | uniq -s 9 > CHANGELOG.md

      - name: Get milestone issues
        id: issues
        uses: quotidian-ennui/find-matching-issues@v0.1.0
        with:
          query: milestone:${{github.event.milestone.title}}

      - name: Concatenate issues with commits
        uses: ftnext/action-concatenate-files@v1.0.1
        with:
          sources: ${{steps.issues.outputs.path}} CHANGELOG.md
          destination: CHANGELOG.md

      - name: Read changelog file
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: CHANGELOG.md

      - name: Zip release
        run: zip -r Campaign.zip gpu_* CHANGELOG.md

      - name: Upload To Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: "Campaign.zip"
          name: ${{github.event.milestone.title}}
          tag_name: ${{github.event.milestone.title}}
          body: ${{steps.changelog.outputs.content}}
          make_latest: true
