name: Release new version

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'     
        required: true
        default: 'v*.*.*'
      name:
        description: 'Release name'     
        required: true
        default: ''
      description:
        description: 'Release description'     
        required: false
        default: ''
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Zip release
        run: zip -r Campaign.zip gpu_*

      - name: Upload To Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: "Campaign.zip"
          name: ${{github.event.inputs.name}}
          tag_name: ${{github.event.inputs.tag}}
          body: ${{github.event.inputs.description}}
          make_latest: true
